name: Build LC3 Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the LC3 project workspace folder'
        required: true
        type: string
      configuration_name:
        description: 'Name of the build configuration (as defined in the .iecplc file)'
        required: true
        type: string

jobs:
  build-project:
    runs-on: [self-hosted, windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run build_project.bat
      run: scripts\build_project.bat "${{ github.event.inputs.project_name }}" "${{ github.event.inputs.configuration_name }}"
