name: Import LC3 Project

on:
  workflow_dispatch:
    inputs:
      project_path:
        description: 'Full path to the LC3 project to import'
        required: true
        type: string

jobs:
  import-project:
    runs-on: [self-hosted, windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run import_project.bat
      run: scripts\import_project.bat "${{ github.event.inputs.project_path }}"
