name: PiL Test

on:
  workflow_dispatch:
    inputs:
      project_name:
        required: true
        type: string
      test_suite:
        required: true
        type: string
      output_path:
        required: true
        type: string
      output_file:
        required: true
        type: string
      release_library_name_version:
        required: false
        type: string

jobs:
  pil-test:
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v3
    - run: scripts\pil_test.bat "${{ github.event.inputs.project_name }}" "${{ github.event.inputs.test_suite }}" "${{ github.event.inputs.output_path }}" "${{ github.event.inputs.output_file }}" "${{ github.event.inputs.release_library_name_version }}"
